[package]
name = "cymothoida_server"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/users.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
